In [59]:
import os
import pandas as pd
from sqlalchemy import create_engine
from dotenv import load_dotenv
import json
from collections import defaultdict

In [60]:
load_dotenv()

PG_USER = os.getenv('PG_USER')
PG_PASSWORD = os.getenv('PG_PASSWORD')
PG_HOST = os.getenv('PG_HOST')
PG_PORT = os.getenv('PG_PORT')
PG_DATABASE = os.getenv('PG_DATABASE')

In [61]:

engine = create_engine(f'postgresql+psycopg2://{PG_USER}:{PG_PASSWORD}@localhost:{PG_PORT}/{PG_DATABASE}')

df_table = pd.read_sql_table('events', engine)

df_table

,id,sender_id,type_name,timestamp,intent_name,action_name,data
0,17474,84f9ee569af8461191bf3ab0c393369f,action,1.723402e+09,None,action_session_start,"{""event"": ""action"", ""timestamp"": 1723402308.92..."
1,17475,84f9ee569af8461191bf3ab0c393369f,session_started,1.723402e+09,None,None,"{""event"": ""session_started"", ""timestamp"": 1723..."
2,17476,84f9ee569af8461191bf3ab0c393369f,action,1.723402e+09,None,action_listen,"{""event"": ""action"", ""timestamp"": 1723402308.92..."
3,17477,84f9ee569af8461191bf3ab0c393369f,user,1.723402e+09,saudações,None,"{""event"": ""user"", ""timestamp"": 1723402309.5533..."
4,17478,84f9ee569af8461191bf3ab0c393369f,user_featurization,1.723402e+09,None,None,"{""event"": ""user_featurization"", ""timestamp"": 1..."
...,...,...,...,...,...,...,...
267,17741,f8e67a2cafa648939f127adb3db62aa8,bot,1.723419e+09,None,None,"{""event"": ""bot"", ""timestamp"": 1723419011.27375..."
268,17742,f8e67a2cafa648939f127adb3db62aa8,slot,1.723419e+09,None,fallback_count,"{""event"": ""slot"", ""timestamp"": 1723419011.2737..."
269,17743,f8e67a2cafa648939f127adb3db62aa8,action,1.723419e+09,None,action_custom_fallback,"{""event"": ""action"", ""timestamp"": 1723419011.33..."
270,17744,f8e67a2cafa648939f127adb3db62aa8,bot,1.723419e+09,None,None,"{""event"": ""bot"", ""timestamp"": 1723419011.33546..."
271,17745,f8e67a2cafa648939f127adb3db62aa8,slot,1.723419e+09,None,fallback_count,"{""event"": ""slot"", ""timestamp"": 1723419011.3354..."

In [62]:
df_chatbot=df_table[["sender_id","type_name","intent_name","action_name","data"]]
df_chatbot

,sender_id,type_name,intent_name,action_name,data
0,84f9ee569af8461191bf3ab0c393369f,action,None,action_session_start,"{""event"": ""action"", ""timestamp"": 1723402308.92..."
1,84f9ee569af8461191bf3ab0c393369f,session_started,None,None,"{""event"": ""session_started"", ""timestamp"": 1723..."
2,84f9ee569af8461191bf3ab0c393369f,action,None,action_listen,"{""event"": ""action"", ""timestamp"": 1723402308.92..."
3,84f9ee569af8461191bf3ab0c393369f,user,saudações,None,"{""event"": ""user"", ""timestamp"": 1723402309.5533..."
4,84f9ee569af8461191bf3ab0c393369f,user_featurization,None,None,"{""event"": ""user_featurization"", ""timestamp"": 1..."
...,...,...,...,...,...
267,f8e67a2cafa648939f127adb3db62aa8,bot,None,None,"{""event"": ""bot"", ""timestamp"": 1723419011.27375..."
268,f8e67a2cafa648939f127adb3db62aa8,slot,None,fallback_count,"{""event"": ""slot"", ""timestamp"": 1723419011.2737..."
269,f8e67a2cafa648939f127adb3db62aa8,action,None,action_custom_fallback,"{""event"": ""action"", ""timestamp"": 1723419011.33..."
270,f8e67a2cafa648939f127adb3db62aa8,bot,None,None,"{""event"": ""bot"", ""timestamp"": 1723419011.33546..."
271,f8e67a2cafa648939f127adb3db62aa8,slot,None,fallback_count,"{""event"": ""slot"", ""timestamp"": 1723419011.3354..."

:

In [53]:
df_chatbot["type_name"].value_counts()

type_name
action    84
slot      71
bot       54
user      27
Name: count, dtype: int64

In [56]:
df_chatbot = df_chatbot.loc[df_chatbot["type_name"].isin(["user", "bot", "slot","action"])]
df_chatbot

,sender_id,type_name,intent_name,action_name,data
0,84f9ee569af8461191bf3ab0c393369f,action,None,action_session_start,"{""event"": ""action"", ""timestamp"": 1723402308.92..."
2,84f9ee569af8461191bf3ab0c393369f,action,None,action_listen,"{""event"": ""action"", ""timestamp"": 1723402308.92..."
3,84f9ee569af8461191bf3ab0c393369f,user,saudações,None,"{""event"": ""user"", ""timestamp"": 1723402309.5533..."
5,84f9ee569af8461191bf3ab0c393369f,action,None,utter_saudações,"{""event"": ""action"", ""timestamp"": 1723402309.56..."
6,84f9ee569af8461191bf3ab0c393369f,bot,None,None,"{""event"": ""bot"", ""timestamp"": 1723402309.56782..."
...,...,...,...,...,...
267,f8e67a2cafa648939f127adb3db62aa8,bot,None,None,"{""event"": ""bot"", ""timestamp"": 1723419011.27375..."
268,f8e67a2cafa648939f127adb3db62aa8,slot,None,fallback_count,"{""event"": ""slot"", ""timestamp"": 1723419011.2737..."
269,f8e67a2cafa648939f127adb3db62aa8,action,None,action_custom_fallback,"{""event"": ""action"", ""timestamp"": 1723419011.33..."
270,f8e67a2cafa648939f127adb3db62aa8,bot,None,None,"{""event"": ""bot"", ""timestamp"": 1723419011.33546..."
271,f8e67a2cafa648939f127adb3db62aa8,slot,None,fallback_count,"{""event"": ""slot"", ""timestamp"": 1723419011.3354..."

In [55]:
df_chatbot[["type_name","intent_name","action_name","data"]]
df_chatbot.head(60)

,sender_id,type_name,intent_name,action_name,data
0,84f9ee569af8461191bf3ab0c393369f,action,None,action_session_start,"{""event"": ""action"", ""timestamp"": 1723402308.92..."
1,84f9ee569af8461191bf3ab0c393369f,session_started,None,None,"{""event"": ""session_started"", ""timestamp"": 1723..."
2,84f9ee569af8461191bf3ab0c393369f,action,None,action_listen,"{""event"": ""action"", ""timestamp"": 1723402308.92..."
3,84f9ee569af8461191bf3ab0c393369f,user,saudações,None,"{""event"": ""user"", ""timestamp"": 1723402309.5533..."
4,84f9ee569af8461191bf3ab0c393369f,user_featurization,None,None,"{""event"": ""user_featurization"", ""timestamp"": 1..."
5,84f9ee569af8461191bf3ab0c393369f,action,None,utter_saudações,"{""event"": ""action"", ""timestamp"": 1723402309.56..."
6,84f9ee569af8461191bf3ab0c393369f,bot,None,None,"{""event"": ""bot"", ""timestamp"": 1723402309.56782..."
7,84f9ee569af8461191bf3ab0c393369f,action,None,utter_show_options,"{""event"": ""action"", ""timestamp"": 1723402309.57..."
8,84f9ee569af8461191bf3ab0c393369f,bot,None,None,"{""event"": ""bot"", ""timestamp"": 1723402309.57894..."
9,84f9ee569af8461191bf3ab0c393369f,action,None,action_listen,"{""event"": ""action"", ""timestamp"": 1723402309.59..."
10,84f9ee569af8461191bf3ab0c393369f,user,marcar_consulta,None,"{""event"": ""user"", ""timestamp"": 1723402310.8589..."
11,84f9ee569af8461191bf3ab0c393369f,user_featurization,None,None,"{""event"": ""user_featurization"", ""timestamp"": 1..."
12,84f9ee569af8461191bf3ab0c393369f,action,None,utter_marcar_consulta,"{""event"": ""action"", ""timestamp"": 1723402310.87..."
13,84f9ee569af8461191bf3ab0c393369f,bot,None,None,"{""event"": ""bot"", ""timestamp"": 1723402310.87937..."
14,84f9ee569af8461191bf3ab0c393369f,action,None,action_listen,"{""event"": ""action"", ""timestamp"": 1723402310.89..."
15,84f9ee569af8461191bf3ab0c393369f,bot,None,None,"{""event"": ""bot"", ""timestamp"": 1723402454.71341..."
16,84f9ee569af8461191bf3ab0c393369f,action,None,action_listen,"{""event"": ""action"", ""timestamp"": 1723402454.72..."
17,84f9ee569af8461191bf3ab0c393369f,user,concordancia,None,"{""event"": ""user"", ""timestamp"": 1723402312.7307..."
18,84f9ee569af8461191bf3ab0c393369f,user_featurization,None,None,"{""event"": ""user_featurization"", ""timestamp"": 1..."
19,84f9ee569af8461191bf3ab0c393369f,action,None,utter_verifica_cadastro,"{""event"": ""action"", ""timestamp"": 1723402312.74..."
20,84f9ee569af8461191bf3ab0c393369f,bot,None,None,"{""event"": ""bot"", ""timestamp"": 1723402312.74465..."
21,84f9ee569af8461191bf3ab0c393369f,action,None,action_listen,"{""event"": ""action"", ""timestamp"": 1723402312.75..."
22,84f9ee569af8461191bf3ab0c393369f,user,negacao,None,"{""event"": ""user"", ""timestamp"": 1723402314.9023..."
23,84f9ee569af8461191bf3ab0c393369f,user_featurization,None,None,"{""event"": ""user_featurization"", ""timestamp"": 1..."
24,84f9ee569af8461191bf3ab0c393369f,action,None,utter_inform_form,"{""event"": ""action"", ""timestamp"": 1723402314.91..."
25,84f9ee569af8461191bf3ab0c393369f,bot,None,None,"{""event"": ""bot"", ""timestamp"": 1723402314.91739..."
26,84f9ee569af8461191bf3ab0c393369f,action,None,cadastro_form,"{""event"": ""action"", ""timestamp"": 1723402315.01..."
27,84f9ee569af8461191bf3ab0c393369f,active_loop,None,cadastro_form,"{""event"": ""active_loop"", ""timestamp"": 17234023..."
28,84f9ee569af8461191bf3ab0c393369f,slot,None,requested_slot,"{""event"": ""slot"", ""timestamp"": 1723402315.0175..."
29,84f9ee569af8461191bf3ab0c393369f,bot,None,None,"{""event"": ""bot"", ""timestamp"": 1723402315.01752..."
30,84f9ee569af8461191bf3ab0c393369f,action,None,action_listen,"{""event"": ""action"", ""timestamp"": 1723402315.03..."
31,eeea83b00a20431196e3430451bb2f23,user_featurization,None,None,"{""event"": ""user_featurization"", ""timestamp"": 1..."
32,eeea83b00a20431196e3430451bb2f23,action,None,utter_saudações,"{""event"": ""action"", ""timestamp"": 1723402597.18..."
33,84f9ee569af8461191bf3ab0c393369f,user,metodo_de_pagamento,None,"{""event"": ""user"", ""timestamp"": 1723402318.1847..."
34,84f9ee569af8461191bf3ab0c393369f,slot,None,nome,"{""event"": ""slot"", ""timestamp"": 1723402318.1854..."
35,84f9ee569af8461191bf3ab0c393369f,user_featurization,None,None,"{""event"": ""user_featurization"", ""timestamp"": 1..."
36,84f9ee569af8461191bf3ab0c393369f,action,None,cadastro_form,"{""event"": ""action"", ""timestamp"": 1723402318.24..."
37,84f9ee569af8461191bf3ab0c393369f,slot,None,nome,"{""event"": ""slot"", ""timestamp"": 1723402318.2449..."
38,84f9ee569af8461191bf3ab0c393369f,slot,None,requested_slot,"{""event"": ""slot"", ""timestamp"": 1723402318.2449..."
39,84f9ee569af8461191bf3ab0c393369f,bot,None,None,"{""event"": ""bot"", ""timestamp"": 1723402318.24494..."
40,84f9ee569af8461191bf3ab0c393369f,action,None,action_listen,"{""event"": ""action"", ""timestamp"": 1723402318.25..."
41,84f9ee569af8461191bf3ab0c393369f,user,metodo_de_pagamento,None,"{""event"": ""user"", ""timestamp"": 1723402445.4146..."
42,84f9ee569af8461191bf3ab0c393369f,slot,None,cpf,"{""event"": ""slot"", ""timestamp"": 1723402445.4153..."
43,84f9ee569af8461191bf3ab0c393369f,user_featurization,None,None,"{""event"": ""user_featurization"", ""timestamp"": 1..."
44,84f9ee569af8461191bf3ab0c393369f,action,None,cadastro_form,"{""event"": ""action"", ""timestamp"": 1723402445.47..."
45,84f9ee569af8461191bf3ab0c393369f,slot,None,cpf,"{""event"": ""slot"", ""timestamp"": 1723402445.4740..."
46,84f9ee569af8461191bf3ab0c393369f,slot,None,requested_slot,"{""event"": ""slot"", ""timestamp"": 1723402445.4741..."
47,84f9ee569af8461191bf3ab0c393369f,bot,None,None,"{""event"": ""bot"", ""timestamp"": 1723402445.47410..."
48,84f9ee569af8461191bf3ab0c393369f,action,None,action_listen,"{""event"": ""action"", ""timestamp"": 1723402445.48..."
49,eeea83b00a20431196e3430451bb2f23,bot,None,None,"{""event"": ""bot"", ""timestamp"": 1723402597.18737..."
50,84f9ee569af8461191bf3ab0c393369f,user,metodo_de_pagamento,None,"{""event"": ""user"", ""timestamp"": 1723402447.9660..."
51,84f9ee569af8461191bf3ab0c393369f,slot,None,time,"{""event"": ""slot"", ""timestamp"": 1723402447.9669..."
52,84f9ee569af8461191bf3ab0c393369f,slot,None,data_nascimento,"{""event"": ""slot"", ""timestamp"": 1723402447.9669..."
53,84f9ee569af8461191bf3ab0c393369f,user_featurization,None,None,"{""event"": ""user_featurization"", ""timestamp"": 1..."
54,84f9ee569af8461191bf3ab0c393369f,action,None,cadastro_form,"{""event"": ""action"", ""timestamp"": 1723402448.03..."
55,84f9ee569af8461191bf3ab0c393369f,slot,None,data_nascimento,"{""event"": ""slot"", ""timestamp"": 1723402448.0306..."
56,84f9ee569af8461191bf3ab0c393369f,slot,None,time,"{""event"": ""slot"", ""timestamp"": 1723402448.0306..."
57,84f9ee569af8461191bf3ab0c393369f,slot,None,requested_slot,"{""event"": ""slot"", ""timestamp"": 1723402448.0306..."
58,84f9ee569af8461191bf3ab0c393369f,bot,None,None,"{""event"": ""bot"", ""timestamp"": 1723402448.03064..."
59,84f9ee569af8461191bf3ab0c393369f,action,None,action_listen,"{""event"": ""action"", ""timestamp"": 1723402448.04..."

In [57]:
def decode_unicode_escapes(text):
    try:
        return text.encode('latin1').decode('unicode_escape').encode('latin1').decode('utf-8')
    except (AttributeError, UnicodeDecodeError):
        return text

def extract_data(row):
    try:
        data = json.loads(row['data'])
    except json.JSONDecodeError as e:
        print(f"Erro ao decodificar JSON: {e}")
        return None

    if row['type_name'] in ['user', 'bot']:
        return {
            'type_name': row['type_name'],
            'text': decode_unicode_escapes(data.get('text', '')),
            'timestamp': data.get('timestamp')
        }
    elif row['type_name'] == 'slot':
        slot_name = data.get('name')
        slot_value = data.get('value')
        if slot_name == 'requested_slot' or slot_value is None:
            return None
        return {
            'type_name': row['type_name'],
            'slot_name': slot_name,
            'slot_value': slot_value,
            'timestamp': data.get('timestamp')
        }
    return None

df_chatbot['extracted_data'] = df_chatbot.apply(extract_data, axis=1)

session_data = defaultdict(lambda: {'messages': [], 'slots': defaultdict(list), 'intent_names': set()})

for _, row in df_chatbot.iterrows():
    session_id = row['sender_id']
    extracted_data = row['extracted_data']
    
    if extracted_data is None:
        continue 

    if row['type_name'] in ['user', 'bot']:
        session_data[session_id]['messages'].append(extracted_data)
    elif row['type_name'] == 'slot':
        slot_name = extracted_data['slot_name']
        slot_value = extracted_data['slot_value']
        if slot_value not in session_data[session_id]['slots'][slot_name]:
            session_data[session_id]['slots'][slot_name].append(slot_value)
        session_data[session_id]['messages'].append({
            'type_name': 'slot',
            'slot_name': slot_name,
            'slot_value': slot_value,
            'timestamp': extracted_data['timestamp']
        })
    
    if row['intent_name']:
        session_data[session_id]['intent_names'].add(row['intent_name'])

for session_id in session_data:
    #order das mensagens
    session_data[session_id]['messages'].sort(key=lambda x: x['timestamp'])
    #pega as intencoes da conversa num list
    session_data[session_id]['intent_names'] = list(session_data[session_id]['intent_names'])
    #filtra os valolres dos slots q sao false, null, nan, '' 
for session_id in session_data:
    session_data[session_id]['slots'] = {key: value for key, value in session_data[session_id]['slots'].items() if value}

session_data_json = json.dumps(session_data, indent=2, ensure_ascii=False)
print(session_data_json)

with open('session_data.json', 'w', encoding='utf-8') as f:
    f.write(session_data_json)

slot_statistics = defaultdict(int)
intent_statistics = defaultdict(int)


for session in session_data.values():
    for slot_name, slot_list in session['slots'].items():
        slot_statistics[slot_name] += len(slot_list)
    for intent in session['intent_names']:
        intent_statistics[intent] += 1

{
  "84f9ee569af8461191bf3ab0c393369f": {
    "messages": [
      {
        "type_name": "user",
        "text": "oi",
        "timestamp": 1723402309.553336
      },
      {
        "type_name": "bot",
        "text": "Oi! Que bom te ver por aqui!!!",
        "timestamp": 1723402309.567828
      },
      {
        "type_name": "bot",
        "text": "No que posso te ajudar?",
        "timestamp": 1723402309.5789454
      },
      {
        "type_name": "user",
        "text": "/marcar_consulta",
        "timestamp": 1723402310.8589442
      },
      {
        "type_name": "bot",
        "text": "Deseja marcar uma consulta conosco?",
        "timestamp": 1723402310.8793721
      },
      {
        "type_name": "user",
        "text": "isso",
        "timestamp": 1723402312.7307787
      },
      {
        "type_name": "bot",
        "text": "Só pra checar, você já tem cadastro com a gente?",
        "timestamp": 1723402312.7446506
      },
      {
        "type_name": "user",
        "text": "nao tenho",
        "timestamp": 1723402314.9023368
      },
      {
        "type_name": "bot",
        "text": "Para usar dos nossos serviços você deve fazer um pequeno cadastro com a gente",
        "timestamp": 1723402314.9173903
      },
      {
        "type_name": "bot",
        "text": "Antes de tudo, me diga seu nome completo, por favor?",
        "timestamp": 1723402315.017526
      },
      {
        "type_name": "user",
        "text": "vandinho",
        "timestamp": 1723402318.1847987
      },
      {
        "type_name": "slot",
        "slot_name": "nome",
        "slot_value": "vandinho",
        "timestamp": 1723402318.185457
      },
      {
        "type_name": "slot",
        "slot_name": "nome",
        "slot_value": "vandinho",
        "timestamp": 1723402318.2449374
      },
      {
        "type_name": "bot",
        "text": "Me passa seu CPF? Precisamos dele para te identificar no nosso sistema",
        "timestamp": 1723402318.2449484
      },
      {
        "type_name": "user",
        "text": "12312312300",
        "timestamp": 1723402445.414693
      },
      {
        "type_name": "slot",
        "slot_name": "cpf",
        "slot_value": "12312312300",
        "timestamp": 1723402445.4153888
      },
      {
        "type_name": "slot",
        "slot_name": "cpf",
        "slot_value": "12312312300",
        "timestamp": 1723402445.4740949
      },
      {
        "type_name": "bot",
        "text": "Qual é a sua data de nascimento?",
        "timestamp": 1723402445.4741054
      },
      {
        "type_name": "user",
        "text": "13/06/2002",
        "timestamp": 1723402447.9660218
      },
      {
        "type_name": "slot",
        "slot_name": "time",
        "slot_value": "2002-06-13T00:00:00.000-03:00",
        "timestamp": 1723402447.9669642
      },
      {
        "type_name": "slot",
        "slot_name": "data_nascimento",
        "slot_value": "13/06/2002",
        "timestamp": 1723402447.9669728
      },
      {
        "type_name": "slot",
        "slot_name": "data_nascimento",
        "slot_value": "13/06/2002",
        "timestamp": 1723402448.0306334
      },
      {
        "type_name": "bot",
        "text": "Agora informe seu email",
        "timestamp": 1723402448.030646
      },
      {
        "type_name": "user",
        "text": "me@gmail.com",
        "timestamp": 1723402454.6507556
      },
      {
        "type_name": "slot",
        "slot_name": "email",
        "slot_value": "me@gmail.com",
        "timestamp": 1723402454.6516657
      },
      {
        "type_name": "slot",
        "slot_name": "email",
        "slot_value": "me@gmail.com",
        "timestamp": 1723402454.7134085
      },
      {
        "type_name": "bot",
        "text": "Por fim, informe seu telefone celular",
        "timestamp": 1723402454.7134194
      },
      {
        "type_name": "user",
        "text": "43931923912",
        "timestamp": 1723402512.0006583
      },
      {
        "type_name": "slot",
        "slot_name": "telefone",
        "slot_value": "43931923912",
        "timestamp": 1723402512.0017228
      },
      {
        "type_name": "slot",
        "slot_name": "telefone",
        "slot_value": "43931923912",
        "timestamp": 1723402512.0654244
      },
      {
        "type_name": "bot",
        "text": "Falha ao cadastrar o usuário. Tente novamente.",
        "timestamp": 1723402512.1782749
      },
      {
        "type_name": "slot",
        "slot_name": "login_sucess",
        "slot_value": false,
        "timestamp": 1723402512.1782804
      },
      {
        "type_name": "bot",
        "text": "Desculpe não conseguimos te cadastrar em nosso sistema, parece que houve um erro. Tente novamente mais tarde!",
        "timestamp": 1723402512.199497
      }
    ],
    "slots": {
      "nome": [
        "vandinho"
      ],
      "cpf": [
        "12312312300"
      ],
      "time": [
        "2002-06-13T00:00:00.000-03:00"
      ],
      "data_nascimento": [
        "13/06/2002"
      ],
      "email": [
        "me@gmail.com"
      ],
      "telefone": [
        "43931923912"
      ],
      "login_sucess": [
        false
      ]
    },
    "intent_names": [
      "concordancia",
      "saudações",
      "negacao",
      "metodo_de_pagamento",
      "marcar_consulta"
    ]
  },
  "eeea83b00a20431196e3430451bb2f23": {
    "messages": [
      {
        "type_name": "user",
        "text": "oi",
        "timestamp": 1723402597.1751316
      },
      {
        "type_name": "bot",
        "text": "Oi! Que bom te ver por aqui!!!",
        "timestamp": 1723402597.1873703
      },
      {
        "type_name": "bot",
        "text": "No que posso te ajudar?",
        "timestamp": 1723402597.1976633
      },
      {
        "type_name": "user",
        "text": "/marcar_consulta",
        "timestamp": 1723402598.0011003
      },
      {
        "type_name": "bot",
        "text": "Deseja marcar uma consulta conosco?",
        "timestamp": 1723402598.0234783
      },
      {
        "type_name": "user",
        "text": "sim",
        "timestamp": 1723402599.1779292
      },
      {
        "type_name": "bot",
        "text": "Só pra checar, você já tem cadastro com a gente?",
        "timestamp": 1723402599.191312
      },
      {
        "type_name": "user",
        "text": "nao tenho",
        "timestamp": 1723402600.9733727
      },
      {
        "type_name": "bot",
        "text": "Para usar dos nossos serviços você deve fazer um pequeno cadastro com a gente",
        "timestamp": 1723402600.986157
      },
      {
        "type_name": "bot",
        "text": "Antes de tudo, me diga seu nome completo, por favor?",
        "timestamp": 1723402601.0857055
      },
      {
        "type_name": "user",
        "text": "vanderson rosa",
        "timestamp": 1723402604.3458667
      },
      {
        "type_name": "slot",
        "slot_name": "nome",
        "slot_value": "vanderson rosa",
        "timestamp": 1723402604.346605
      },
      {
        "type_name": "slot",
        "slot_name": "nome",
        "slot_value": "vanderson rosa",
        "timestamp": 1723402604.411594
      },
      {
        "type_name": "bot",
        "text": "Me passa seu CPF? Precisamos dele para te identificar no nosso sistema",
        "timestamp": 1723402604.4116056
      },
      {
        "type_name": "user",
        "text": "09877890914",
        "timestamp": 1723402610.5590403
      },
      {
        "type_name": "slot",
        "slot_name": "cpf",
        "slot_value": "09877890914",
        "timestamp": 1723402610.5597835
      },
      {
        "type_name": "slot",
        "slot_name": "cpf",
        "slot_value": "09877890914",
        "timestamp": 1723402610.6243696
      },
      {
        "type_name": "bot",
        "text": "Qual é a sua data de nascimento?",
        "timestamp": 1723402610.6243808
      },
      {
        "type_name": "user",
        "text": "13/06/2002",
        "timestamp": 1723402612.6141498
      },
      {
        "type_name": "slot",
        "slot_name": "time",
        "slot_value": "2002-06-13T00:00:00.000-03:00",
        "timestamp": 1723402612.6152644
      },
      {
        "type_name": "slot",
        "slot_name": "data_nascimento",
        "slot_value": "13/06/2002",
        "timestamp": 1723402612.6152737
      },
      {
        "type_name": "slot",
        "slot_name": "data_nascimento",
        "slot_value": "13/06/2002",
        "timestamp": 1723402612.6786551
      },
      {
        "type_name": "bot",
        "text": "Agora informe seu email",
        "timestamp": 1723402612.6786687
      },
      {
        "type_name": "user",
        "text": "me@gmail.com",
        "timestamp": 1723402614.9494884
      },
      {
        "type_name": "slot",
        "slot_name": "email",
        "slot_value": "me@gmail.com",
        "timestamp": 1723402614.9505112
      },
      {
        "type_name": "slot",
        "slot_name": "email",
        "slot_value": "me@gmail.com",
        "timestamp": 1723402615.0110133
      },
      {
        "type_name": "bot",
        "text": "Por fim, informe seu telefone celular",
        "timestamp": 1723402615.0110245
      },
      {
        "type_name": "user",
        "text": "493912391392",
        "timestamp": 1723402616.1900947
      },
      {
        "type_name": "slot",
        "slot_name": "telefone",
        "slot_value": "493912391392",
        "timestamp": 1723402616.1910124
      },
      {
        "type_name": "slot",
        "slot_name": "telefone",
        "slot_value": "493912391392",
        "timestamp": 1723402616.2583373
      },
      {
        "type_name": "slot",
        "slot_name": "login_sucess",
        "slot_value": true,
        "timestamp": 1723402616.340101
      },
      {
        "type_name": "bot",
        "text": "E tá tudo certo! Seu cadastro foi concluído com sucesso",
        "timestamp": 1723402616.3573432
      },
      {
        "type_name": "bot",
        "text": "Ops, acho que não entendi. Você poderia repetir?",
        "timestamp": 1723402616.4166243
      },
      {
        "type_name": "slot",
        "slot_name": "fallback_count",
        "slot_value": 1.0,
        "timestamp": 1723402616.416633
      },
      {
        "type_name": "bot",
        "text": "Desculpe, não entendi o que deseja",
        "timestamp": 1723402616.4717984
      },
      {
        "type_name": "bot",
        "text": "No que posso te ajudar?",
        "timestamp": 1723402616.4718049
      },
      {
        "type_name": "slot",
        "slot_name": "fallback_count",
        "slot_value": 0.0,
        "timestamp": 1723402616.471807
      },
      {
        "type_name": "bot",
        "text": "Ops, acho que não entendi. Você poderia repetir?",
        "timestamp": 1723402616.55213
      },
      {
        "type_name": "slot",
        "slot_name": "fallback_count",
        "slot_value": 1.0,
        "timestamp": 1723402616.5521386
      },
      {
        "type_name": "bot",
        "text": "Desculpe, não entendi o que deseja",
        "timestamp": 1723402616.616763
      },
      {
        "type_name": "bot",
        "text": "No que posso te ajudar?",
        "timestamp": 1723402616.6167693
      },
      {
        "type_name": "slot",
        "slot_name": "fallback_count",
        "slot_value": 0.0,
        "timestamp": 1723402616.6167717
      },
      {
        "type_name": "bot",
        "text": "Ops, acho que não entendi. Você poderia repetir?",
        "timestamp": 1723402616.6787963
      },
      {
        "type_name": "slot",
        "slot_name": "fallback_count",
        "slot_value": 1.0,
        "timestamp": 1723402616.6788023
      },
      {
        "type_name": "bot",
        "text": "Desculpe, não entendi o que deseja",
        "timestamp": 1723402616.744098
      },
      {
        "type_name": "bot",
        "text": "No que posso te ajudar?",
        "timestamp": 1723402616.7441046
      },
      {
        "type_name": "slot",
        "slot_name": "fallback_count",
        "slot_value": 0.0,
        "timestamp": 1723402616.7441068
      },
      {
        "type_name": "bot",
        "text": "Ops, acho que não entendi. Você poderia repetir?",
        "timestamp": 1723402616.8060822
      },
      {
        "type_name": "slot",
        "slot_name": "fallback_count",
        "slot_value": 1.0,
        "timestamp": 1723402616.8060882
      }
    ],
    "slots": {
      "cpf": [
        "09877890914"
      ],
      "nome": [
        "vanderson rosa"
      ],
      "time": [
        "2002-06-13T00:00:00.000-03:00"
      ],
      "data_nascimento": [
        "13/06/2002"
      ],
      "email": [
        "me@gmail.com"
      ],
      "telefone": [
        "493912391392"
      ],
      "login_sucess": [
        true
      ],
      "fallback_count": [
        1.0,
        0.0
      ]
    },
    "intent_names": [
      "concordancia",
      "saudações",
      "negacao",
      "metodo_de_pagamento",
      "nlu_fallback",
      "marcar_consulta"
    ]
  },
  "f8e67a2cafa648939f127adb3db62aa8": {
    "messages": [
      {
        "type_name": "user",
        "text": "oi",
        "timestamp": 1723418995.9846177
      },
      {
        "type_name": "bot",
        "text": "Oi! Que bom te ver por aqui!!!",
        "timestamp": 1723418995.9962323
      },
      {
        "type_name": "bot",
        "text": "No que posso te ajudar?",
        "timestamp": 1723418996.0059812
      },
      {
        "type_name": "user",
        "text": "/marcar_consulta",
        "timestamp": 1723418996.6646645
      },
      {
        "type_name": "bot",
        "text": "Deseja marcar uma consulta conosco?",
        "timestamp": 1723418996.6845288
      },
      {
        "type_name": "user",
        "text": "sim",
        "timestamp": 1723418997.8070147
      },
      {
        "type_name": "bot",
        "text": "Só pra checar, você já tem cadastro com a gente?",
        "timestamp": 1723418997.820986
      },
      {
        "type_name": "user",
        "text": "nao",
        "timestamp": 1723418999.2309673
      },
      {
        "type_name": "bot",
        "text": "Para usar dos nossos serviços você deve fazer um pequeno cadastro com a gente",
        "timestamp": 1723418999.246713
      },
      {
        "type_name": "bot",
        "text": "Antes de tudo, me diga seu nome completo, por favor?",
        "timestamp": 1723418999.363349
      },
      {
        "type_name": "user",
        "text": "vand",
        "timestamp": 1723419000.7016742
      },
      {
        "type_name": "slot",
        "slot_name": "nome",
        "slot_value": "vand",
        "timestamp": 1723419000.702329
      },
      {
        "type_name": "slot",
        "slot_name": "nome",
        "slot_value": "vand",
        "timestamp": 1723419000.7629883
      },
      {
        "type_name": "bot",
        "text": "Me passa seu CPF? Precisamos dele para te identificar no nosso sistema",
        "timestamp": 1723419000.7629988
      },
      {
        "type_name": "user",
        "text": "88827391922",
        "timestamp": 1723419004.3389685
      },
      {
        "type_name": "slot",
        "slot_name": "cpf",
        "slot_value": "88827391922",
        "timestamp": 1723419004.3396585
      },
      {
        "type_name": "slot",
        "slot_name": "cpf",
        "slot_value": "88827391922",
        "timestamp": 1723419004.4032319
      },
      {
        "type_name": "bot",
        "text": "Qual é a sua data de nascimento?",
        "timestamp": 1723419004.403243
      },
      {
        "type_name": "user",
        "text": "13/06/2002",
        "timestamp": 1723419006.1072624
      },
      {
        "type_name": "slot",
        "slot_name": "time",
        "slot_value": "2002-06-13T00:00:00.000-03:00",
        "timestamp": 1723419006.108234
      },
      {
        "type_name": "slot",
        "slot_name": "data_nascimento",
        "slot_value": "13/06/2002",
        "timestamp": 1723419006.1082428
      },
      {
        "type_name": "slot",
        "slot_name": "data_nascimento",
        "slot_value": "13/06/2002",
        "timestamp": 1723419006.1747904
      },
      {
        "type_name": "bot",
        "text": "Agora informe seu email",
        "timestamp": 1723419006.1748037
      },
      {
        "type_name": "user",
        "text": "me@gmail.com",
        "timestamp": 1723419009.2288706
      },
      {
        "type_name": "slot",
        "slot_name": "email",
        "slot_value": "me@gmail.com",
        "timestamp": 1723419009.2298446
      },
      {
        "type_name": "slot",
        "slot_name": "email",
        "slot_value": "me@gmail.com",
        "timestamp": 1723419009.2932472
      },
      {
        "type_name": "bot",
        "text": "Por fim, informe seu telefone celular",
        "timestamp": 1723419009.2932572
      },
      {
        "type_name": "user",
        "text": "4393921931293",
        "timestamp": 1723419010.710771
      },
      {
        "type_name": "slot",
        "slot_name": "telefone",
        "slot_value": "4393921931293",
        "timestamp": 1723419010.7118108
      },
      {
        "type_name": "slot",
        "slot_name": "telefone",
        "slot_value": "4393921931293",
        "timestamp": 1723419010.773741
      },
      {
        "type_name": "slot",
        "slot_name": "login_sucess",
        "slot_value": true,
        "timestamp": 1723419010.8902385
      },
      {
        "type_name": "bot",
        "text": "E tá tudo certo! Seu cadastro foi concluído com sucesso",
        "timestamp": 1723419010.9086015
      },
      {
        "type_name": "bot",
        "text": "Ops, acho que não entendi. Você poderia repetir?",
        "timestamp": 1723419010.97383
      },
      {
        "type_name": "slot",
        "slot_name": "fallback_count",
        "slot_value": 1.0,
        "timestamp": 1723419010.9738357
      },
      {
        "type_name": "bot",
        "text": "Desculpe, não entendi o que deseja",
        "timestamp": 1723419011.0347066
      },
      {
        "type_name": "bot",
        "text": "No que posso te ajudar?",
        "timestamp": 1723419011.0347145
      },
      {
        "type_name": "slot",
        "slot_name": "fallback_count",
        "slot_value": 0.0,
        "timestamp": 1723419011.0347183
      },
      {
        "type_name": "bot",
        "text": "Ops, acho que não entendi. Você poderia repetir?",
        "timestamp": 1723419011.092747
      },
      {
        "type_name": "slot",
        "slot_name": "fallback_count",
        "slot_value": 1.0,
        "timestamp": 1723419011.092753
      },
      {
        "type_name": "bot",
        "text": "Desculpe, não entendi o que deseja",
        "timestamp": 1723419011.152485
      },
      {
        "type_name": "bot",
        "text": "No que posso te ajudar?",
        "timestamp": 1723419011.1524923
      },
      {
        "type_name": "slot",
        "slot_name": "fallback_count",
        "slot_value": 0.0,
        "timestamp": 1723419011.1524956
      },
      {
        "type_name": "bot",
        "text": "Ops, acho que não entendi. Você poderia repetir?",
        "timestamp": 1723419011.211349
      },
      {
        "type_name": "slot",
        "slot_name": "fallback_count",
        "slot_value": 1.0,
        "timestamp": 1723419011.2113543
      },
      {
        "type_name": "bot",
        "text": "Desculpe, não entendi o que deseja",
        "timestamp": 1723419011.2737367
      },
      {
        "type_name": "bot",
        "text": "No que posso te ajudar?",
        "timestamp": 1723419011.273752
      },
      {
        "type_name": "slot",
        "slot_name": "fallback_count",
        "slot_value": 0.0,
        "timestamp": 1723419011.2737541
      },
      {
        "type_name": "bot",
        "text": "Ops, acho que não entendi. Você poderia repetir?",
        "timestamp": 1723419011.3354638
      },
      {
        "type_name": "slot",
        "slot_name": "fallback_count",

/tmp/ipykernel_62309/1547292584.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_chatbot['extracted_data'] = df_chatbot.apply(extract_data, axis=1)

In [58]:
filtered_intents = []

for i in range(len(df_chatbot) - 1):
    current_row = df_chatbot.iloc[i]
    next_row = df_chatbot.iloc[i + 1]
    
    # Verifica se a linha atual é uma intenção de usuário
    if current_row['type_name'] == 'user' and current_row['intent_name']:
        intent_name = current_row['intent_name']
        
        # Verifica se a próxima linha é a ação correspondente
        if next_row['type_name'] == 'action' and next_row['action_name'] == f'utter_{intent_name}':
            filtered_intents.append(intent_name)

# Convertendo para um DataFrame (se desejar)
filtered_df = pd.DataFrame(filtered_intents, columns=['filtered_intent'])

# Exibindo as intenções filtradas
filtered_df

   filtered_intent
0        saudações
1  marcar_consulta
2  marcar_consulta
3        saudações
4  marcar_consulta